### ISSUE TITLE
non-averaged features

### ISSUE THREAD

**Issue by joushua97** [ExplainableML/TCAF-GZSL#1]
Can you please share the extracted non-averaged features of the VGGSound and ActivityNet datasets?

**Comment by MerceaOtniel** [comment]
The other two datasets are very big and they would not fit in the gdrive link I shared in the github. We will try to find a way of loading these features somewhere so that others can access them.

**Comment by hummelth** [comment]
We updated the README with download links for the non-averaged features of VGGSound-GZSL and ActivityNet-GZSL :)

**Comment by joushua97** [comment]
Thanks a lot!
