### ISSUE TITLE
non-averaged features about SeLaVi

### ISSUE THREAD

**Issue by Uaena-cf** [ExplainableML/TCAF-GZSL#11]
I'm very sorry to bother you. When I use the features from SeLaVi, I encounter a dimension mismatch error. I would like to ask if you have faced this issue and how you resolved it?
<img width="1076" alt="截屏2024-09-14 22 09 00" src="https://github.com/user-attachments/assets/3ebf39da-a871-4b7b-b600-719e4e85a5b0">
When I try to print the shape of `self.data["audio"]["data"]`, I find that they are all quite different. I would like to ask what the reason for this might be?
<img width="280" alt="截屏2024-09-14 22 09 27" src="https://github.com/user-attachments/assets/8415791d-3c5e-4b71-b6e3-901e1351812f">
Thank you once again!

**Comment by MerceaOtniel** [comment]
Hi.

No, we did not encounter this error. Where do you get the error? In the dataloader?


They are different because videos have different lengths. Some videos are shorter, some are longer, thus, it varies. The first dimension represents how many features are in that specific video, which corresponds with the length of the video.

**Comment by Uaena-cf** [comment]
> Hi.
> 
> No, we did not encounter this error. Where do you get the error? In the dataloader?
> 
> They are different because videos have different lengths. Some videos are shorter, some are longer, thus, it varies. The first dimension represents how many features are in that specific video, which corresponds with the length of the video.

Yes, that's correct, in the `all_data` method of the dataset.py. I would like to ask how you handle these features of different lengths for subsequent tasks? 

Thank you for taking the time to respond!

**Comment by MerceaOtniel** [comment]
we load them, as you can see, with different lengths, and afterwards we pad them. In each batch, all the sequences have the same length. That happens in DefaultCollator function in dataset.py

**Comment by Uaena-cf** [comment]
> we load them, as you can see, with different lengths, and afterwards we pad them. In each batch, all the sequences have the same length. That happens in DefaultCollator function in dataset.py

Oh, I see! I think I understand now. Thank you very much for answering my questions!
