### ISSUE TITLE
train error

### ISSUE THREAD

**Issue by xiaoxinning** [ExplainableML/TCAF-GZSL#12]
![屏幕截图 2024-09-14 220245](https://github.com/user-attachments/assets/7a13542a-dc9d-4715-8ffa-0e5a918748f9)
thank you for your code.why it turns out like this when using UCF to train. i use the command 
python3 main.py --cfg /root/autodl-tmp/TCAF-GZSL/config/best/best_cls/best_ucf.yaml  --root_dir avgzsl_benchmark_non_averaged_datasets/UCF --log_dir networks/activitynet_cls --dataset_name UCF --run all

**Comment by MerceaOtniel** [comment]
It may be numpy version or other libraries have changed since the code was published. Try to use the same versions as in our environment (if you didn't do it already).

Other people have also managed to use our code and get results, so the code should not be a problem.
