### ISSUE TITLE
performance on the UCF dataset

### ISSUE THREAD

**Issue by joushua97** [ExplainableML/TCAF-GZSL#2]
I trained the model using the code and features on the UCF dataset but obtained the results which are much worse than that in the paper:
Seen performance=25.92, Unseen performance=36.23, GZSL performance=30.22, ZSL performance=36.47
Could you please tell me the possible reasons for the results?

**Comment by MerceaOtniel** [comment]
Hi. This is strange. Have you checked to make sure that you have the exact same version of the libraries as the ones in this repo (TCAF.yaml)? Moreover, what GPU do you use to train the models?

**Comment by joushua97** [comment]
Yes, I have the exact same version of the libraries as the ones in this repo. I use NVIDIA RTX A6000 to train the models.

This is the eval.log file:
INFO - 08/20/22 02:10:46 - 0:00:00 - Start evaluation /home/xz/projects/TCAF-GZSL-master/logs/Aug20_01-56-44_756090_dell-PowerEdge-T640
INFO - 08/20/22 02:10:46 - 0:00:00 - ale: False
                                     apn: False
                                     attention_fusion: False
                                     audio_baseline: False
                                     baseline: False
                                     batch_seqlen_test: max
                                     batch_seqlen_test_maxlen: 300
                                     batch_seqlen_test_trim: center
                                     cjme: False
                                     concatenated_baseline: False
                                     dataset_name: UCF
                                     device: cuda
                                     devise: False
                                     eval_bs: 64
                                     eval_name: Attention
                                     eval_num_workers: 8
                                     eval_save_performances: False
                                     load_path_stage_A: /home/xz/projects/TCAF-GZSL-master/logs/Aug19_23-03-41_030323_dell-PowerEdge-T640
                                     load_path_stage_B: /home/xz/projects/TCAF-GZSL-master/logs/Aug20_01-56-44_756090_dell-PowerEdge-T640
                                     new_model: False
                                     new_model_attention: False
                                     new_model_attention_both_heads: False
                                     new_model_early_fusion: False
                                     new_model_middle_fusion: False
                                     new_model_sequence: True
                                     perceiver: False
                                     root_dir: /home/xz/projects/TCAF-GZSL-master/UCF
                                     sje: False
                                     video_baseline: False
INFO - 08/20/22 02:10:46 - 0:00:00 - Loaded configuration /home/xz/projects/TCAF-GZSL-master/logs/Aug20_01-56-44_756090_dell-PowerEdge-T640/args.pkl
INFO - 08/20/22 02:10:46 - 0:00:00 - additional_dropout: 0.1
                                     additional_triplets_loss: False
                                     ale: False
                                     apn: False
                                     attention_fusion: False
                                     audio_baseline: False
                                     audio_only: False
                                     baseline: False
                                     batch_seqlen_test: max
                                     batch_seqlen_test_maxlen: 300
                                     batch_seqlen_test_trim: center
                                     batch_seqlen_train: max
                                     batch_seqlen_train_maxlen: 60
                                     batch_seqlen_train_trim: random
                                     bs: 64
                                     cfg: /home/xz/projects/TCAF-GZSL-master/config/best/best_cls/best_ucf.yaml
                                     cjme: False
                                     concatenated_baseline: False
                                     cross_entropy_loss: True
                                     ct_loss: False
                                     cycle_loss: False
                                     dataset_name: UCF
                                     debug: False
                                     debug_comment: 
                                     decoder_dropout: 0.1
                                     decoder_hidden_size: 512
                                     decoder_use_bn: False
                                     depth_transformer: 1
                                     device: cuda
                                     devise: False
                                     distance_fn: L2Loss
                                     embedding_dropout: 0.3
                                     embedding_use_bn: False
                                     embeddings_batch_norm: True
                                     embeddings_hidden_size: 512
                                     epochs: 4
                                     eval_bs: 64
                                     eval_name: Attention
                                     eval_num_workers: 8
                                     eval_save_performances: False
                                     exp_name: 
                                     feature_extraction_method: cls_features_non_averaged
                                     first_additional_triplet: 1
                                     input_size: None
                                     input_size_audio: 128
                                     input_size_video: 4096
                                     load_path_stage_A: None
                                     load_path_stage_B: None
                                     log_dir: /home/xz/projects/TCAF-GZSL-master/logs
                                     lr: 7e-05
                                     lr_scheduler: True
                                     manual_text_word2vec: False
                                     margin: 1.0
                                     mixup_parameter: 0.5
                                     n_batches: 300
                                     new_model: False
                                     new_model_attention: False
                                     new_model_attention_both_heads: False
                                     new_model_early_fusion: False
                                     new_model_middle_fusion: False
                                     new_model_sequence: True
                                     norm_inputs: False
                                     normalize_decoder_outputs: False
                                     optimizer: adam
                                     perceiver: False
                                     rec_loss: True
                                     reg_loss: True
                                     retrain_all: True
                                     root_dir: /home/xz/projects/TCAF-GZSL-master/UCF
                                     run: all
                                     save_checkpoints: True
                                     second_additional_triplet: 1
                                     seed: 42
                                     selavi: False
                                     sje: False
                                     third_additional_triplet: 1
                                     transformer_average_features: False
                                     transformer_depth: 6
                                     transformer_dim: 300
                                     transformer_dim_head: 64
                                     transformer_dropout: 0.3
                                     transformer_embedding_dim: 64
                                     transformer_embedding_dropout: 0.2
                                     transformer_embedding_embed_augment_position: False
                                     transformer_embedding_fourier_scale: 10.0
                                     transformer_embedding_modality: True
                                     transformer_embedding_time_embed_type: sinusoid
                                     transformer_embedding_time_len: 120
                                     transformer_heads: 8
                                     transformer_mlp_dim: 128
                                     transformer_use_class_token: True
                                     transformer_use_embedding_net: True
                                     use_cross_attention: True
                                     use_mixup: False
                                     use_self_attention: False
                                     val_all_loss: False
                                     verbose: False
                                     video_baseline: False
                                     video_only: False
                                     w_loss: False
                                     z_score_inputs: False
                                     zero_shot_split: cls_split
INFO - 08/20/22 02:10:46 - 0:00:00 - The evaluation will be stored in /home/xz/projects/TCAF-GZSL-master/logs/Aug20_01-56-44_756090_dell-PowerEdge-T640
                                     

INFO - 08/20/22 02:10:46 - 0:00:00 - Initializing Dataset UCFDataset	Dataset split: val	Zero shot mode: None
INFO - 08/20/22 02:10:46 - 0:00:00 - Loading processed data from disk from /home/xz/projects/TCAF-GZSL-master/avgzsl_benchmark_non_averaged_datasets/UCF/_features_processed/cls_features_non_averaged/valcls_split.pkl
INFO - 08/20/22 02:10:46 - 0:00:00 - Initializing Dataset UCFDataset	Dataset split: test	Zero shot mode: None
INFO - 08/20/22 02:10:46 - 0:00:00 - Loading processed data from disk from /home/xz/projects/TCAF-GZSL-master/avgzsl_benchmark_non_averaged_datasets/UCF/_features_processed/cls_features_non_averaged/testcls_split.pkl
INFO - 08/20/22 02:10:47 - 0:00:01 - Initializing Dataset ContrastiveDataset	Based on Dataset: UCFDataset	with split: val
INFO - 08/20/22 02:10:47 - 0:00:01 - Initializing Dataset ContrastiveDataset	Based on Dataset: UCFDataset	with split: test
INFO - 08/20/22 02:10:48 - 0:00:02 - Created network [Multimodal_Sequence_Transformer] with total number of parameters: 7.3 million.
INFO - 08/20/22 02:10:48 - 0:00:02 - Multimodal_Sequence_Transformer(
                                       (A_enc): EmbeddingNet(
                                         (fc): Sequential(
                                           (0): Linear(in_features=128, out_features=512, bias=True)
                                           (1): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
                                           (2): ReLU()
                                           (3): Dropout(p=0.3, inplace=False)
                                           (4): Linear(in_features=512, out_features=300, bias=True)
                                           (5): BatchNorm1d(300, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
                                           (6): ReLU()
                                           (7): Dropout(p=0.3, inplace=False)
                                         )
                                       )
                                       (V_enc): EmbeddingNet(
                                         (fc): Sequential(
                                           (0): Linear(in_features=4096, out_features=512, bias=True)
                                           (1): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
                                           (2): ReLU()
                                           (3): Dropout(p=0.3, inplace=False)
                                           (4): Linear(in_features=512, out_features=300, bias=True)
                                           (5): BatchNorm1d(300, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
                                           (6): ReLU()
                                           (7): Dropout(p=0.3, inplace=False)
                                         )
                                       )
                                       (W_proj): EmbeddingNet(
                                         (fc): Sequential(
                                           (0): Linear(in_features=300, out_features=64, bias=True)
                                           (1): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
                                           (2): ReLU()
                                           (3): Dropout(p=0.1, inplace=False)
                                         )
                                       )
                                       (D_w): EmbeddingNet(
                                         (fc): Sequential(
                                           (0): Linear(in_features=64, out_features=300, bias=True)
                                           (1): BatchNorm1d(300, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
                                           (2): ReLU()
                                           (3): Dropout(p=0.1, inplace=False)
                                         )
                                       )
                                       (position_encoder_block): AudioVisualEmbedding(
                                         (modal_embedding): Embedding(2, 64)
                                         (fourier_embeddings): Linear(in_features=64, out_features=64, bias=True)
                                         (pad_embedding): Embedding(1, 64)
                                         (dropout): Dropout(p=0.2, inplace=False)
                                         (out_proj_audio): Conv1d(364, 300, kernel_size=(1,), stride=(1,))
                                         (out_proj_video): Conv1d(364, 300, kernel_size=(1,), stride=(1,))
                                       )
                                       (audiovisual_embeddings): AudioVisualEmbedding(
                                         (modal_embedding): Embedding(2, 64)
                                         (fourier_embeddings): Linear(in_features=64, out_features=64, bias=True)
                                         (pad_embedding): Embedding(1, 64)
                                         (dropout): Dropout(p=0.2, inplace=False)
                                         (out_proj_audio): Conv1d(364, 300, kernel_size=(1,), stride=(1,))
                                         (out_proj_video): Conv1d(364, 300, kernel_size=(1,), stride=(1,))
                                       )
                                       (Audio_visual_transformer): Transformer(
                                         (layers): ModuleList(
                                           (0): TransformerLayer(
                                             (attn): NewAttention(
                                               (to_q): Linear(in_features=300, out_features=512, bias=False)
                                               (to_k): Linear(in_features=300, out_features=512, bias=False)
                                               (to_v): Linear(in_features=300, out_features=512, bias=False)
                                               (to_out): Sequential(
                                                 (0): Linear(in_features=512, out_features=300, bias=True)
                                                 (1): Dropout(p=0.3, inplace=False)
                                               )
                                               (attend): Softmax(dim=-1)
                                             )
                                             (ff): FeedForward(
                                               (net): Sequential(
                                                 (0): Linear(in_features=300, out_features=128, bias=True)
                                                 (1): GELU()
                                                 (2): Dropout(p=0.3, inplace=False)
                                                 (3): Linear(in_features=128, out_features=300, bias=True)
                                                 (4): Dropout(p=0.3, inplace=False)
                                               )
                                             )
                                             (norm): LayerNorm((300,), eps=1e-05, elementwise_affine=True)
                                           )
                                           (1): TransformerLayer(
                                             (attn): NewAttention(
                                               (to_q): Linear(in_features=300, out_features=512, bias=False)
                                               (to_k): Linear(in_features=300, out_features=512, bias=False)
                                               (to_v): Linear(in_features=300, out_features=512, bias=False)
                                               (to_out): Sequential(
                                                 (0): Linear(in_features=512, out_features=300, bias=True)
                                                 (1): Dropout(p=0.3, inplace=False)
                                               )
                                               (attend): Softmax(dim=-1)
                                             )
                                             (ff): FeedForward(
                                               (net): Sequential(
                                                 (0): Linear(in_features=300, out_features=128, bias=True)
                                                 (1): GELU()
                                                 (2): Dropout(p=0.3, inplace=False)
                                                 (3): Linear(in_features=128, out_features=300, bias=True)
                                                 (4): Dropout(p=0.3, inplace=False)
                                               )
                                             )
                                             (norm): LayerNorm((300,), eps=1e-05, elementwise_affine=True)
                                           )
                                           (2): TransformerLayer(
                                             (attn): NewAttention(
                                               (to_q): Linear(in_features=300, out_features=512, bias=False)
                                               (to_k): Linear(in_features=300, out_features=512, bias=False)
                                               (to_v): Linear(in_features=300, out_features=512, bias=False)
                                               (to_out): Sequential(
                                                 (0): Linear(in_features=512, out_features=300, bias=True)
                                                 (1): Dropout(p=0.3, inplace=False)
                                               )
                                               (attend): Softmax(dim=-1)
                                             )
                                             (ff): FeedForward(
                                               (net): Sequential(
                                                 (0): Linear(in_features=300, out_features=128, bias=True)
                                                 (1): GELU()
                                                 (2): Dropout(p=0.3, inplace=False)
                                                 (3): Linear(in_features=128, out_features=300, bias=True)
                                                 (4): Dropout(p=0.3, inplace=False)
                                               )
                                             )
                                             (norm): LayerNorm((300,), eps=1e-05, elementwise_affine=True)
                                           )
                                           (3): TransformerLayer(
                                             (attn): NewAttention(
                                               (to_q): Linear(in_features=300, out_features=512, bias=False)
                                               (to_k): Linear(in_features=300, out_features=512, bias=False)
                                               (to_v): Linear(in_features=300, out_features=512, bias=False)
                                               (to_out): Sequential(
                                                 (0): Linear(in_features=512, out_features=300, bias=True)
                                                 (1): Dropout(p=0.3, inplace=False)
                                               )
                                               (attend): Softmax(dim=-1)
                                             )
                                             (ff): FeedForward(
                                               (net): Sequential(
                                                 (0): Linear(in_features=300, out_features=128, bias=True)
                                                 (1): GELU()
                                                 (2): Dropout(p=0.3, inplace=False)
                                                 (3): Linear(in_features=128, out_features=300, bias=True)
                                                 (4): Dropout(p=0.3, inplace=False)
                                               )
                                             )
                                             (norm): LayerNorm((300,), eps=1e-05, elementwise_affine=True)
                                           )
                                           (4): TransformerLayer(
                                             (attn): NewAttention(
                                               (to_q): Linear(in_features=300, out_features=512, bias=False)
                                               (to_k): Linear(in_features=300, out_features=512, bias=False)
                                               (to_v): Linear(in_features=300, out_features=512, bias=False)
                                               (to_out): Sequential(
                                                 (0): Linear(in_features=512, out_features=300, bias=True)
                                                 (1): Dropout(p=0.3, inplace=False)
                                               )
                                               (attend): Softmax(dim=-1)
                                             )
                                             (ff): FeedForward(
                                               (net): Sequential(
                                                 (0): Linear(in_features=300, out_features=128, bias=True)
                                                 (1): GELU()
                                                 (2): Dropout(p=0.3, inplace=False)
                                                 (3): Linear(in_features=128, out_features=300, bias=True)
                                                 (4): Dropout(p=0.3, inplace=False)
                                               )
                                             )
                                             (norm): LayerNorm((300,), eps=1e-05, elementwise_affine=True)
                                           )
                                           (5): TransformerLayer(
                                             (attn): NewAttention(
                                               (to_q): Linear(in_features=300, out_features=512, bias=False)
                                               (to_k): Linear(in_features=300, out_features=512, bias=False)
                                               (to_v): Linear(in_features=300, out_features=512, bias=False)
                                               (to_out): Sequential(
                                                 (0): Linear(in_features=512, out_features=300, bias=True)
                                                 (1): Dropout(p=0.3, inplace=False)
                                               )
                                               (attend): Softmax(dim=-1)
                                             )
                                             (ff): FeedForward(
                                               (net): Sequential(
                                                 (0): Linear(in_features=300, out_features=128, bias=True)
                                                 (1): GELU()
                                                 (2): Dropout(p=0.3, inplace=False)
                                                 (3): Linear(in_features=128, out_features=300, bias=True)
                                                 (4): Dropout(p=0.3, inplace=False)
                                               )
                                             )
                                             (norm): LayerNorm((300,), eps=1e-05, elementwise_affine=True)
                                           )
                                         )
                                       )
                                       (O_proj): EmbeddingNet(
                                         (fc): Sequential(
                                           (0): Linear(in_features=300, out_features=512, bias=True)
                                           (1): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
                                           (2): ReLU()
                                           (3): Dropout(p=0.1, inplace=False)
                                           (4): Linear(in_features=512, out_features=64, bias=True)
                                           (5): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
                                           (6): ReLU()
                                           (7): Dropout(p=0.1, inplace=False)
                                         )
                                       )
                                       (D_o): EmbeddingNet(
                                         (fc): Sequential(
                                           (0): Linear(in_features=64, out_features=512, bias=True)
                                           (1): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
                                           (2): ReLU()
                                           (3): Dropout(p=0.1, inplace=False)
                                           (4): Linear(in_features=512, out_features=300, bias=True)
                                           (5): BatchNorm1d(300, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
                                           (6): ReLU()
                                           (7): Dropout(p=0.1, inplace=False)
                                         )
                                       )
                                       (criterion_cyc): MSELoss()
                                       (criterion_cls): CrossEntropyLoss()
                                       (MSE_loss): MSELoss()
                                     )
INFO - 08/20/22 02:10:48 - 0:00:02 - Loading model weights from /home/xz/projects/TCAF-GZSL-master/logs/Aug19_23-03-41_030323_dell-PowerEdge-T640/Multimodal_Sequence_Transformer_score.pt
INFO - 08/20/22 02:10:48 - 0:00:02 - Load from epoch: 4
INFO - 08/20/22 02:10:48 - 0:00:02 - Loading model weights from /home/xz/projects/TCAF-GZSL-master/logs/Aug20_01-56-44_756090_dell-PowerEdge-T640/checkpoints/Multimodal_Sequence_Transformer_score_ckpt_3.pt
INFO - 08/20/22 02:10:48 - 0:00:02 - Load from epoch: 4
INFO - 08/20/22 02:10:55 - 0:00:10 - Validation betas:	Audio=2.799999952316284	Video=2.799999952316284	Both=2.799999952316284
INFO - 08/20/22 02:10:55 - 0:00:10 - Best beta combined: 2.7999999523496175
INFO - 08/20/22 02:11:01 - 0:00:15 - 
                                                         Seen performance=25.92, Unseen performance=36.23, GZSL performance=30.22, ZSL performance=36.47 
                                                         
INFO - 08/20/22 02:11:01 - 0:00:15 - FINISHED

**Comment by MerceaOtniel** [comment]
Hello,
We couldn't find a reason for this from the log above.
You could try to first reproduce our results from the model checkpoints we provided. For further reference, all our training and eval logs are provided in the uploaded model checkpoint files.

**Comment by PHDJieFu** [comment]
@joushua97 Hello, on UCF benchmark, we also reproduce the similar results as yours (Seen performance=35.69, Unseen performance=31.36, GZSL performance=33.39, ZSL performance=33.57), Have you solved your problem?

**Comment by xia-zhe** [comment]
I am experiencing the same problem,  how you are solving it?
