### ISSUE TITLE
Fail to obtain SeLaVi features

### ISSUE THREAD

**Issue by daan1838** [ExplainableML/TCAF-GZSL#3]
When I tried to extract SeLaVi features, it failed with the following error message:

Bad audio of video: /root/share/dataset/UCF-101/train/ApplyEyeMakeup/v_ApplyEyeMakeup_g01_c01.avi
Failed to decode by pyav with exception: local variable 'spec' referenced before assignment
Index: 0.

Could you please tell me how to solve this problem?

**Comment by MerceaOtniel** [comment]
Hello. 
We were not able to replicate this issue but your error message suggest that the audio track of the video file is corrupted or is missing.

**Comment by hummelth** [comment]
We have  added download links for the temporal SeLaVi features to the [README](https://github.com/ExplainableML/TCAF-GZSL#download-features).
