### ISSUE TITLE
download  vggsound dataset error

### ISSUE THREAD

**Issue by hollow1024** [ExplainableML/TCAF-GZSL#4]
When I download the vggsound dataset, I have the following problem

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>SlowDown</Code>
<Message>Please reduce your request rate.</Message>
<Resource>/tcaf-gzsl/vggsound-supervised-temporal.zip</Resource>
<RequestId>938257731876353961</RequestId>
</Error>

**Comment by hummelth** [comment]
Thanks for making us aware of this. We are on it and will let you know once the dataset files are reachable again.

**Comment by hummelth** [comment]
The issue has been fixed and the dataset files are available again.

**Comment by linimor** [comment]
I'm sorry to bother you but this dataset is no longer available.

**Comment by hummelth** [comment]
Thanks for letting us know, the VGGSound dataset is available again. Please check the README for the new download links.
