### ISSUE TITLE
Some code is missing in splitting_scripts

### ISSUE THREAD

**Issue by daan1838** [ExplainableML/TCAF-GZSL#8]
Hello, I'm try to get my own features with your code.
The code to create the .h5 file does not exist in splitting_scripts_main/create_features_selavi.py and splitting_scripts/create_features.py

I'm try to adapt your code in AVCA repository, but it's not working out well.
Can you help me solve this problem?

**Comment by MerceaOtniel** [comment]
Hi. 
The code works and it can be used for extracting everything that is needed. But we will provide shortly a simplified version of those scripts.

**Comment by MerceaOtniel** [comment]
We changed the scripts so that now they are easier to be used. The scripts can be found in the same folders.
